name: Datadog Code Security

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  datadog-static-analysis:
    name: Datadog SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Datadog Static Analysis
        uses: DataDog/datadog-static-analyzer-github-action@v3
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_site: datadoghq.com
          dd_service: ${{ github.event.repository.name }}
          dd_env: ci

  datadog-sca:
    name: Datadog SCA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Datadog SCA
        uses: DataDog/datadog-sca-github-action@v2
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_site: datadoghq.com
          dd_service: ${{ github.event.repository.name }}
          dd_env: ci
